// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyLocalizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "EasyLocalizer.ccda0abc-3ca7-40fd-928b-fb61f99d9c4d";
        public const string Name = "EasyLocalizer";
        public const string Description = @"EasyLocalizer is a Visual Studio extension that makes translating your application a breeze. With a simple right‑click (or alt+ctrl+R), you can pull any piece of text into your resource files and instantly replace it in code with a neat lookup. The built‑in dialog automatically discovers all your localized resource files (for example, French, Russian, etc.) and lets you enter translations side by side. Your settings—like the lookup prefix and which .resx file to use—are remembered between sessions. It even knows not to wrap something twice if it’s already localized. Keyboard shortcuts and smart selection handling mean you spend less time fiddling with quotes and more time writing features. Overall, EasyLocalizer streamlines the process of extracting, translating, and maintaining strings in your app, so you can focus on what really matters.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Vizzey";
        public const string Tags = "Localize, Localization, DI, blazor, razor, C#";
        public const bool IsPreview = false;
    }
}
