// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyLocalizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "EasyLocalizer.ccda0abc-3ca7-40fd-928b-fb61f99d9c4d";
        public const string Name = "EasyLocalizer";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vizzey";
        public const string Tags = "";
    }
}
