// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyLocalizer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TestString = "a6f9d371-c156-467c-ab35-9a8f0c3cf528";
        public static Guid Test = new Guid(TestString);

        public const string VSMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid VSMainMenu = new Guid(VSMainMenuString);

        public const string guidImagesString = "8c001c71-d720-4fa0-ab16-89afb73411ed";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LocalizeCommandId = 0x0100;
        public const int LocalizeMenuGroup = 0x0001;
        public const int IDM_VS_CTXT_TEXTEDITOR = 0x040D;
    }
}
