// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyLocalizer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string testIconString = "753d6636-6ca6-4d52-a8be-d48ae361ac3a";
        public static Guid testIcon = new Guid(testIconString);

        public const string TestString = "a6f9d371-c156-467c-ab35-9a8f0c3cf528";
        public static Guid Test = new Guid(TestString);

        public const string VSMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid VSMainMenu = new Guid(VSMainMenuString);

        public const string MyImagesString = "8c001c71-d720-4fa0-ab16-89afb73411ed";
        public static Guid MyImages = new Guid(MyImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int testIcon1 = 0x0001;
        public const int LocalizeMenuGroup = 0x0001;
        public const int LocalizeCommandId = 0x0100;
        public const int IDM_VS_CTXT_TEXTEDITOR = 0x040D;
        public const int LocalizeIcon = 0x0001;
    }
}
